# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Biofields' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Biofields

pod 'RealmSwift' 
pod 'Alamofire' 
pod 'AlamofireObjectMapper'
pod 'STPopup'
pod 'SwiftSpinner'
pod 'IQKeyboardManagerSwift'
pod 'Kingfisher'
pod 'Fabric'
pod 'Crashlytics'
pod 'CryptoSwift'
pod 'SpaceView'
pod 'Zip', '~> 0.7'

end
